const ProgramData = [
    {
        id:1,
        programImage: {
            photo1:"https://images.unsplash.com/photo-1664575197593-2e7085ef086b?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        },
        programName:"Back2LIFE Reintegration & Transition Support Program",
        subHeader: "Back2LIFE Reintegration & Transition Support collaborates with individuals, both men and women, residing at the Schenectady County Jail. Our aim is to reduce recidivism rates and bolster public safety across the County. To achieve this, our program operates with a Reintegration & Transition Team comprising six members.",
       programPgraphs: {
        paragraph1: "Our Intake Coordinator conducts assessments for individuals staying in the facility for more than seven days. This process aims to understand the circumstances surrounding their arrest and detention. The objective is to identify challenges leading to negative interactions with the system and to develop tailored plans to address these challenges during their stay. This approach equips them with skills to better manage their lives upon release.",
        paragraph2: "The Inmate Services & Programs Coordinator ensures that individuals housed at the facility have essential access to their families, legal representation, and court proceedings during their case proceedings. Additionally, they oversee available programs and collaborate with community volunteers to ensure that individuals have access to valuable resources, including classes, training sessions, and spiritual guidance and support.",
        paragraph3: "The Discharge Coordinator meets with individuals sentenced to remain at the county jail and those scheduled for release back into the Schenectady County Community. Their role is to develop a comprehensive transition and reintegration plan for each individual leaving the facility, aimed at stabilizing them and reducing the risk of recidivism. This includes assessing needs such as shelter/housing, community/family support, employment, education/training, and health insurance, among others. The overarching objective is to facilitate stability and connect individuals with the necessary services and resources for a healthy and safe life.",
        paragraph4:"The Community Transition & Reintegration Coach engages with individuals after the development of their discharge plan to closely examine identified needs and initiate the transition process. Their responsibilities include arranging appointments for mental health, substance abuse, Department of Social Services (DSS), and employment resources outlined during discharge planning discussions. Additionally, they reach out to community support networks (such as significant others, parents, children, spiritual representatives, and friends) mentioned during planning to reinforce or re-establish these connections, ensuring individuals have a strong support system upon release. Following their release, the Community Transition & Reintegration Coach conducts in-person and phone check-ins to provide ongoing support and ensure individuals are aware of available assistance.",
        paragraph5:"There are Tier I and Tier II Counselors who meet with those interested in counseling while they are confined, which is also continued upon and after their release. Tier I Counselors meet with individuals who are dealing with lighter issues such as: difficulty adjusting with the environment, usually those confined for their first time; high stress due to the challenge of maintaining their relationship(s) due to being confined; situational anxiety, etc. Tier II Counselors meet with individuals presenting with deeper issues such as depression, uncontrolled anger, loss of a loved one during confinement or a recent loss that the person is still having a difficult time processing on his/her own, etc. Again, these supports are extended even once the time of confinement has ended, and the person is released back to their family."
       }

    },
    {
        id:2,
        programImage: {
            photo1:"https://images.unsplash.com/photo-1664575197593-2e7085ef086b?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            photo2:"https://images.unsplash.com/photo-1573497491208-6b1acb260507?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            photo3: "https://images.unsplash.com/photo-1507537362848-9c7e70b7b5c1?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        },
        programName:"1Life2Live Gun & Gang Violence Prevention & Intervention Program",
        subHeader: "1Life2Live Gun & Gang Violence Prevention & Intervention program aims to decrease the incidence of shots fired, shooting injuries, and homicides across Schenectady County over an extended period.",
        programPgraphs: {
        paragraph1: "The program employs individuals known as the 'Street Team,' comprised of men and women who have previously been part of street culture and possess extensive community relationships and street connections. This enables them to stay informed about conflicts emerging within the community and intervene to resolve them. Additionally, each member of the Street Team is responsible for a caseload of eight (8) individuals identified as Program Participants, who are at high risk of either perpetrating or being victims of shootings. The objective is to connect these individuals with resources aimed at redirecting their behavior, including employment opportunities, vocational and trade training, education, and other supportive services.",
        paragraph2: "In situations where proactive intervention is not possible, and a shooting occurs, the Street Team immediately responds by visiting the location of the incident. They engage with community members and contacts with whom they have established relationships to gain insight into the underlying causes of the conflict. This enables them to work with all parties involved to find resolution.In cases of injury resulting from the shooting, the Street Team also visits the hospital, recognizing it as a critical moment where emotions run high. Their objective is to contain, de-escalate, and mediate the conflict to mitigate the likelihood of retaliation. To achieve this, the Street Team collaborates with all parties involved to facilitate conflict resolution.",
        paragraph3: "At present, the Street Team comprises three members. However, we anticipate receiving additional funding this year, enabling us to expand the team's coverage to more areas. This expansion will strengthen our ability to provide robust support to Program Participants.",
        paragraph4:"The success of the Street Team and the overall program hinges on trust, respect, and credibility. It is imperative to emphasize and uphold these values, which is why stakeholders, including law enforcement and criminal justice entities, understand and respect that information gathered by the Street Team remains confidential and is never shared with law enforcement or the criminal justice system. Clear boundaries are established and honored by all parties involved."
        }
    },
    {
        id:3,
        programImage: {
            photo1:"https://images.unsplash.com/photo-1664575197593-2e7085ef086b?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            photo2:"https://images.unsplash.com/photo-1573497491208-6b1acb260507?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            photo3: "https://images.unsplash.com/photo-1507537362848-9c7e70b7b5c1?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        },
        programName:"L.I.F.E.’s Alternative: L.E.A.D (Let Everyone Advance with Dignity) Diversion Program",
        subHeader: "Our harm-reduction diversion program operates on three key components that form the basis of its success: The Operation Work Group (OWG), Policy Coordinating Group (PCG), and Community Engagement Coordinator(s). These components enable frontline officers to refer individuals confronting mental health, poverty, homelessness, or related challenges away from the criminal justice system. Qualified participants, upon agreement, are enrolled by our Outreach & Intake Coordinator, leading to charge dismissal upon successful completion, while also providing alternative pathways for accessing our program without police involvement.",
        programPgraphs: {
        paragraph1: "Social Contact Referrals serve as a means for community partners and stakeholders to suggest individuals who meet our program's criteria and could gain from joining. Once they fill out a referral form on our website and it's approved by the Project Manager, our Outreach & Intake Coordinator steps in to make contact and guide enrollment. This process closely resembles the one mentioned earlier but differs in that it doesn't involve law enforcement since there's no criminal activity involved.",
        paragraph2:  "Community Contact Referral provides an opportunity for community members or neighbors to recommend individuals who meet our program's criteria and could benefit from participation. By completing a referral form on our website and receiving approval from the Project Manager, our Outreach & Intake Coordinator initiates contact and facilitates enrollment, mirroring the process outlined previously. Notably, this avenue does not involve law enforcement, as there is no criminal activity.",
        paragraph3: "Self-Referral allows individuals who have learned about our program and its level of engagement to approach program staff seeking support for themselves. In this scenario, the Outreach & Intake Coordinator meets with the individual to complete initial paperwork and schedules an appointment with a Case Manager. The Case Manager then guides the individual through the process and connects them with the necessary services.",
        paragraph4:"The Policy Coordinating Group (PCG) comprises community stakeholder leaders with decision-making authority, dedicated to eliminating barriers that exacerbate issues for the program's target population. This group includes representatives from the Schenectady County Sheriff’s Office, Schenectady City Police Department, County Manager District Attorney Office, Office Of the Public Defender, County Department Of Health, Department of Social Services, The Galesi Group, The Melozzi Group, and Youth L.I.F.E. Support Network, Inc. Together, they oversee program operations and convene monthly to ensure its effectiveness.",
        paragraph5:"The Operation Work Group (OWG) is composed of representatives appointed by the members of the PCG, tasked with conducting bi-weekly case reviews for program enrollees to ensure their needs are met and stability is achieved. Additionally, OWG members propose policy changes to better serve the program's population, with the overarching goal of supporting participant success.",
        paragraph6:"The Community Engagement Coordinator(s) who are responsible for educating the community as a whole (community members, neighborhood associations, faith-based groups, mental health providers, substance use agencies, businesses, chambers of commerce, bodegas, super markets, etc.) about the program with the goal of building up a base and network of support to have in place as resources for the men and women that the program will be working with. This coalition/collaboration group is called the Community Leadership Team and is managed by the Community Engagement Coordinator(s). The Community Leadership Team meets frequently and is updated on the progress and challenges met with respect to persons that the Case Managers are working with to be sure that all known resources are at the table and being engaged.",
        }
    },
]
export default ProgramData;